spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:postgresql://localhost:5432/cosmetics"
    username: postgres
    password: postgres
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
